// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRMGY16Y3SA41AnHdHXioU5Mh7tfT-ED4',
    appId: '1:970152274910:android:80a19fd3bf6fa9f97e0b4f',
    messagingSenderId: '970152274910',
    projectId: 'social-app-9a4d2',
    databaseURL: 'https://social-app-9a4d2-default-rtdb.firebaseio.com',
    storageBucket: 'social-app-9a4d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEzRGrG2VpDfSXddMax238jVlg-3erx3Y',
    appId: '1:970152274910:ios:62007d033637c20c7e0b4f',
    messagingSenderId: '970152274910',
    projectId: 'social-app-9a4d2',
    databaseURL: 'https://social-app-9a4d2-default-rtdb.firebaseio.com',
    storageBucket: 'social-app-9a4d2.firebasestorage.app',
    iosBundleId: 'com.example.blocSocialApp',
  );
}
